-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggmNZ1oREOBSGEEmt
7WtbaLMnkTRDEwtfSm5qtHI3ZCSgCgYIKoZIzj0DAQehRANCAAQ0qFsCHttGTlEg
j5OCKHFQX8hUzYf0PzpG9NSeyE4lQxqnY3EHCDItqWuBVhnnBoskBOioFK64O9C6
FUnvpKUK
-----END PRIVATE KEY-----