// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfogV3wVgTj0u6LIy9Tf8va9Lw9eoHjo8',
    appId: '1:354237870385:web:b9cd8dff71e4309597c010',
    messagingSenderId: '354237870385',
    projectId: 'vela-31f91',
    authDomain: 'vela-31f91.firebaseapp.com',
    storageBucket: 'vela-31f91.firebasestorage.app',
    measurementId: 'G-1BY6ZRQLRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7KGBVVYe0RexQOvKmlTvaAPMu5_bNNps',
    appId: '1:354237870385:android:c878a3d93db8e2bc97c010',
    messagingSenderId: '354237870385',
    projectId: 'vela-31f91',
    storageBucket: 'vela-31f91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxKfmk_p67pCqiDKiWubQdL8OjzslKvLs',
    appId: '1:354237870385:ios:d56c12efd517234897c010',
    messagingSenderId: '354237870385',
    projectId: 'vela-31f91',
    storageBucket: 'vela-31f91.firebasestorage.app',
    androidClientId: '354237870385-u79i4r9edeto84ghdgv5ka48ahpd52i0.apps.googleusercontent.com',
    iosClientId: '354237870385-fh2mnbv6phird2bm0f7q20o0o9hom1ri.apps.googleusercontent.com',
    iosBundleId: 'com.nbekdev.vela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxKfmk_p67pCqiDKiWubQdL8OjzslKvLs',
    appId: '1:354237870385:ios:d56c12efd517234897c010',
    messagingSenderId: '354237870385',
    projectId: 'vela-31f91',
    storageBucket: 'vela-31f91.firebasestorage.app',
    androidClientId: '354237870385-u79i4r9edeto84ghdgv5ka48ahpd52i0.apps.googleusercontent.com',
    iosClientId: '354237870385-fh2mnbv6phird2bm0f7q20o0o9hom1ri.apps.googleusercontent.com',
    iosBundleId: 'com.nbekdev.vela',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfogV3wVgTj0u6LIy9Tf8va9Lw9eoHjo8',
    appId: '1:354237870385:web:453179a2987d237297c010',
    messagingSenderId: '354237870385',
    projectId: 'vela-31f91',
    authDomain: 'vela-31f91.firebaseapp.com',
    storageBucket: 'vela-31f91.firebasestorage.app',
    measurementId: 'G-K3Y6DMW4B6',
  );
}
